export const mockSkills = [
  {
    id: 1,
    title: "JavaScript Tutoring",
    description:
      "Learn JS basics and advanced concepts with hands-on examples.",
    owner: "Alice",
    rating: 4.5,
    tags: ["tech", "education"],
  },
  {
    id: 2,
    title: "Photoshop Editing",
    description: "Get professional photo editing tips and tutorials.",
    owner: "Bob",
    rating: 4.7,
    tags: ["art", "design"],
  },
  {
    id: 3,
    title: "Guitar Lessons",
    description: "Beginner and intermediate guitar lessons online.",
    owner: "Charlie",
    rating: 4.3,
    tags: ["music", "education"],
  },
  {
    id: 4,
    title: "React Help",
    description: "React component guidance and debugging help.",
    owner: "Dana",
    rating: 4.8,
    tags: ["tech", "coding"],
  },
  {
    id: 5,
    title: "Cooking Basics",
    description: "Learn how to prepare simple and healthy meals.",
    owner: "Evelyn",
    rating: 3.2,
    tags: ["cooking", "lifestyle"],
  },
  {
    id: 6,
    title: "Knitting 101",
    description: "Introduction to knitting scarves, hats, and more.",
    owner: "Frank",
    rating: 2.9,
    tags: ["crafts", "art"],
  },
  {
    id: 7,
    title: "Public Speaking Coaching",
    description: "Boost your confidence when presenting to groups.",
    owner: "Grace",
    rating: 4.0,
    tags: ["communication", "career"],
  },
  {
    id: 8,
    title: "Chess Strategy",
    description: "Learn beginner to advanced chess tactics and openings.",
    owner: "Henry",
    rating: 5.0,
    tags: ["games", "education"],
  },
  {
    id: 9,
    title: "Yoga for Beginners",
    description: "Gentle yoga sequences to build flexibility and balance.",
    owner: "Isla",
    rating: 3.8,
    tags: ["fitness", "health"],
  },
  {
    id: 10,
    title: "Carpentry Projects",
    description: "DIY furniture building and woodworking tips.",
    owner: "Jack",
    rating: 2.5,
    tags: ["crafts", "DIY"],
  },
  {
    id: 11,
    title: "Language Exchange: Spanish",
    description: "Practice conversational Spanish with a native speaker.",
    owner: "Karla",
    rating: 4.1,
    tags: ["language", "education"],
  },
  {
    id: 12,
    title: "Basic Car Repair",
    description: "Learn how to change oil, brakes, and do simple fixes.",
    owner: "Leo",
    rating: 3.6,
    tags: ["automotive", "DIY"],
  },
  {
    id: 13,
    title: "Digital Marketing",
    description: "SEO, ads, and social media growth strategies.",
    owner: "Maya",
    rating: 4.9,
    tags: ["business", "tech"],
  },
  {
    id: 14,
    title: "Origami Folding",
    description: "Fun paper folding projects for relaxation.",
    owner: "Nate",
    rating: 1.8,
    tags: ["crafts", "art"],
  },
  {
    id: 15,
    title: "Coding Interview Prep",
    description: "Mock interviews and problem-solving in JavaScript.",
    owner: "Olivia",
    rating: 4.4,
    tags: ["tech", "career"],
  },
  {
    id: 16,
    title: "Pet Training",
    description: "Learn how to teach your dog obedience basics.",
    owner: "Paul",
    rating: 2.1,
    tags: ["pets", "lifestyle"],
  },
  {
    id: 17,
    title: "Photography Basics",
    description: "Learn to shoot, edit, and compose photos like a pro.",
    owner: "Quinn",
    rating: 3.9,
    tags: ["art", "photography"],
  },
  {
    id: 18,
    title: "Meditation Techniques",
    description: "Practice mindfulness and reduce stress with guided sessions.",
    owner: "Riley",
    rating: 4.2,
    tags: ["health", "lifestyle"],
  },
  {
    id: 19,
    title: "Home Gardening",
    description: "Tips for growing vegetables, flowers, and herbs at home.",
    owner: "Sam",
    rating: 3.5,
    tags: ["lifestyle", "DIY", "nature"],
  },
  {
    id: 20,
    title: "Video Editing",
    description: "Learn to edit videos with Premiere Pro or Final Cut.",
    owner: "Tina",
    rating: 4.6,
    tags: ["tech", "design", "media"],
  },
  {
    id: 21,
    title: "Creative Writing",
    description: "Improve your storytelling and writing style.",
    owner: "Uma",
    rating: 2.9,
    tags: ["art", "education", "writing"],
  },
  {
    id: 22,
    title: "Fitness Bootcamp",
    description: "High-intensity workouts to build strength and stamina.",
    owner: "Victor",
    rating: 4.8,
    tags: ["fitness", "health"],
  },
  {
    id: 23,
    title: "Interior Design Tips",
    description: "Learn to style and decorate your living spaces.",
    owner: "Wendy",
    rating: 3.4,
    tags: ["design", "lifestyle", "art"],
  },
  {
    id: 24,
    title: "French Language Basics",
    description: "Learn to speak basic French for travel or study.",
    owner: "Xavier",
    rating: 4.0,
    tags: ["language", "education"],
  },
  {
    id: 25,
    title: "Mobile App Prototyping",
    description: "Create interactive prototypes for mobile apps quickly.",
    owner: "Yara",
    rating: 4.7,
    tags: ["tech", "design", "career"],
  },
  {
    id: 26,
    title: "Birdwatching 101",
    description: "Identify birds and understand their habits in your area.",
    owner: "Zane",
    rating: 3.1,
    tags: ["nature", "hobby", "education"],
  },
  {
    id: 27,
    title: "Knockout Boxing",
    description: "Learn boxing basics and conditioning techniques.",
    owner: "Aiden",
    rating: 2.7,
    tags: ["fitness", "sports"],
  },
];
